name: CI-CD

on:
  push:
    branches: ["master"]
  workflow_dispatch:
jobs:

  #Contrução Pepeline - CI
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Obtendo Código do Projeto
        uses: actions/checkout@v4

      #Configuração Docker Hub
      - name: Autenticar no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Construção e Envio da Imagem Docker - Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./src
          push: true
          file: ./src/Dockerfile
          tags: | 
            maiconandreis/fake-shop:latest
            maiconandreis/fake-shop:v${{ github.run_number }}

  
  #Contrução Pepeline - CD
  cd:
    runs-on: ubuntu-latest
    needs: [ci]
    steps:
      - name: Autenticar AWS
        run: echo "Executando o comando aws configure"
      - name: Configurar o kubectl
        run: echo "Executando o comando aws eks update-kubeconfig"
      - name: Deploy dos Manifestos do Kubernets
        run: echo "Executando o comando bubectl apply"
